version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    depends_on:
      - app
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  app:
    build:
        context: .
        dockerfile: app.dockerfile
    ports:
      - 2112:2112